### ISSUE TITLE
No channels in your discord?

### ISSUE THREAD

**Issue by gitbisector** [HearthstoneAccess/DevTools#1]
Just not yet, maybe? I thought I'd have a look and see if I can help you out.  
A few people I know depend on your great work for Hearthstone. 

Do you need one person to do each Blizzard patch or can working through each patch be a joint effort?

**Comment by Svenja001** [comment]
@gitbisector there are Channels on the Discord

**Comment by JessicaTegner** [comment]
the discord link in the readme is not a valid invite. Basically put, the people that is not currently on the server, can't see the channel

**Comment by gitbisector** [comment]
Can I get a new invite then or you have the support needed to keep it going?

**Comment by inkydragon** [comment]
Just use this link: 

> ### 5.7. Where can I find the Discord server?
>
> You can find an invite link to join the Discord server [here.](https://discord.gg/WZWRenbuRe)
>
> —— https://hearthstoneaccess.github.io/#5.7

**Comment by gitbisector** [comment]
Thx. That worked!
